micronaut:
  application:
    name: example-jdbc
jackson:
  bean-introspection-module: true
---
datasources:
  default:
    url: jdbc:oracle:thin:@mnociatp_high?TNS_ADMIN=/tmp/wallet
    driverClassName: oracle.jdbc.OracleDriver
    username: mnocidemo
    password: ${MICRONAUT_OCI_DEMO_PASSWORD}
    schema-generate: CREATE_DROP
    dialect: ORACLE