micronaut:
  application:
    name: example-jdbc
jackson:
  bean-introspection-module: true
---
wallet:
  TRUSTSTORE_JKS: ${WALLET_TRUSTSTORE_JKS}
  TNSNAMES_ORA: ${WALLET_TNSNAMES_ORA}
  SQLNET_ORA: ${WALLET_SQLNET_ORA}
  OJDBC_PROPERTIES: ${WALLET_OJDBC_PROPERTIES}
  KEYSTORE_JKS: ${WALLET_KEYSTORE_JKS}
  EWALLET_P12: ${WALLET_EWALLET_P12}
  CWALLET_SSO: ${WALLET_CWALLET_SSO}
---