title: "Create a VCN, Compute instance & ATP instance"
stackDescription: "Description..."
schemaVersion: 1.1.0
version: "20200301"
locale: "en"

variableGroups:
- title: ${Messages.solutionsHub.requiredConfig()}
  visible: true  
  variables:
  - ssh_public_key

- title: ${Messages.solutionsHub.optionalConfig()}
  visible: true  
  variables:
  - shape

variables:
  ssh_public_key:
    type: oci:core:ssh:publickey
    additionalProps:
      allowMultiple: true
    required: false
    default: [""]
    pattern: "((^(ssh-rsa AAAAB3NzaC1yc2|ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNT|ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzOD|ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1Mj|ssh-ed25519 AAAAC3NzaC1lZDI1NTE5|ssh-dss AAAAB3NzaC1kc3)[0-9A-Za-z+\/]+[=]{0,3})( [^,]*)?)(,((ssh-rsa AAAAB3NzaC1yc2|ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNT|ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzOD|ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1Mj|ssh-ed25519 AAAAC3NzaC1lZDI1NTE5|ssh-dss AAAAB3NzaC1kc3)[0-9A-Za-z+\/]+[=]{0,3})( [^,]*)?)*$"
    title: ${Messages.solutionsHub.solutions.computeInstance.variables.ssh_public_key.title()}
    description: ${Messages.solutionsHub.solutions.computeInstance.variables.ssh_public_key.description()}

  shape:
    type: oci:core:instanceshape:name
    required: true
    title: ${Messages.solutionsHub.solutions.computeInstance.variables.shape.title()}
    description: ${Messages.solutionsHub.solutions.computeInstance.variables.shape.description()}
    default: "VM.Standard.E2.1.Micro"
    dependsOn:
      compartmentId: tenancy_ocid
