name: mn-data-jdbc-atp-build
on:
  push:
    branches:
      - '*'
jobs:
  build-stack:
    name: Build Stack
    runs-on: ubuntu-latest
    steps:

      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Build Stack'
        run: |
          zip -r stack.zip terraform

      - name: 'Publish Stack'
        uses: actions/upload-artifact@v2-preview
        with:
          name: 'stack.zip'
          path: 'stack.zip'