name: mn-data-jdbc-atp-build
on:
  push:
    branches:
      - '*'
jobs:
  build-stack:
    name: Build Stack
    runs-on: ubuntu-latest
    steps:

      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Build Stack'
        run: |
          pwd
          ls -la terraform/